version: '3'

services:
  app:
    image: rails-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile.dev
    volumes:
      - ./:/app
      - ./db:/app/db  # This line shares the 'db' directory
    tmpfs:
      - /app/tmp/pids
    ports:
      - 3000:3000
    working_dir: /app
    tty: true
    command: docker/app/startup.sh

volumes:
  database:
